name: "HA Notification Tap Repository"
url: "https://github.com/iamjoshk/ha-notification-tap"
maintainer: "Josh K"
slug: "ha_notification_tap"
version: "1.0.0"
description: "A Home Assistant add-on for notification tap actions"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
