name: "HA Notification Tap"
version: "1.0.0"
slug: "ha_notification_tap"
description: "A Home Assistant add-on for notification tap actions"
url: "https://github.com/iamjoshk/ha-notification-tap"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options: {}
schema: {}
