name: "HA Notification Tap"
version: "1.0.0"
slug: "ha_notification_tap"
description: "Handle Home Assistant notification tap actions"
url: "https://github.com/iamjoshk/ha-notification-tap"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: stable
init: false
hassio_api: true
homeassistant_api: true
host_network: true
ingress: true
ingress_port: 8099
panel_icon: mdi:bell-ring
map:
  - share:rw
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web server port"
webui: http://[HOST]:[PORT:8099]
options:
  event_type: "notification_tap"
  actions:
    example_action:
      room: "living_room"
      action: "lights_on"
schema:
  event_type: str
  actions: dict
