name: "HA Notification Tap"
version: "1.0.0"
slug: "ha_notification_tap"
description: "Fire events from notification taps"
url: "https://github.com/iamjoshk/ha-notification-tap"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web server port"
host_network: true
