name: "HA Notification Tap"
version: "0.0.1-alpha.44"
slug: "ha_notification_tap"
description: "Fire events from notification taps"
url: "https://github.com/iamjoshk/ha-notification-tap"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web server port"
options:
  ha_token: "!secret notify_tap_token"
  ha_host: "fhassistant"
  redirect_url: ""  # Empty default = no redirect
  debug: false
schema:
  ha_token: str
  ha_host: str
  redirect_url: match(^(homeassistant://|http://|https://|entityId:|./|noAction|lovelace/|my\.)|$)  # Support all HA URL schemes
  debug: bool
host_network: true
hassio_api: true
init: false
