name: "HA Notification Tap"
version: "0.0.1-alpha.20
slug: "ha_notification_tap"
description: "Fire events from notification taps"
url: "https://github.com/iamjoshk/ha-notification-tap"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
homeassistant_api: true
host_network: true
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web server port"
